.travis.yml, README.md
Fixes: https://github.com/nodesource/ncm-cli/issues/123
=> ci: add travis config & badge

.gitignore, package.json
Unfortunately I cannot upload this to any hosted service I know of because both coveralls and CodeCov require private repo access... :|
=> scripts: add --cov to test, ignore coverage files

commands/whitelist.js
Fixes: https://github.com/nodesource/ncm-cli/issues/91
=> whitelist: fix risk meters

commands/report.js, commands/whitelist.js, test/lib/test-runner.js
Fixes: https://github.com/nodesource/ncm-cli/issues/81
Not the nicest but it'l do.
=> report, whitelist: grab orgId from token if available

commands/details.js, commands/install.js, lib/util.js
Fixes: https://github.com/nodesource/ncm-cli/issues/131
=> util: parse @scope/module@version correctly

package-lock.json, package.json
=> dep updates

commands/report.js, commands/whitelist.js, lib/ncm-style.js, package-lock.json, package.json
- No longer obscures report errors (fixes #100 and #72).
- Moves another signin prompt message around.
- Allows debugging with `DEBUG=`.
=> update / fix error reporting

package.json
No way to do this with npm flags, sadly.
=> scripts: simple change to improve dev testing

commands/install.js
Refs: https://github.com/nodesource/ncm-cli/issues/159
Feel free to merge while I am OOO
=> install: handle errors from child install process

commands/install.js, package-lock.json, package.json
Deals with shell nonsense in Windows spawn().
Fixes https://github.com/nodesource/ncm-cli/issues/159
=> install: use cross-spawn

commands/orgs.js
This could be prettier but this will do.
Fixes: https://github.com/nodesource/ncm-cli/issues/160
=> orgs: ignore expired orgs

lib/client-request.js
See https://github.com/brycebaril/client-request/issues/14
=> client-request: handle timeouts properly

lib/report/module.js
My bad on this one, two minor oversights from 2fe8fa0
Fixes https://github.com/nodesource/ncm-cli/issues/180
=> reporting logic fixes

commands/config.js, commands/whitelist.js, package.json
This PR fixes handling config data as below:
=> fix handling config data

commands/report.js, commands/whitelist.js, lib/report/util.js, package-lock.json, package.json
=> more utilization of quantitative scoring

lib/report/util.js, package-lock.json, package.json
This PR fixes truncate name text to fit within column:
e.g.:
=> fix truncate name text to fit within column

README.md, bin/ncm-cli.js, commands/report.js, commands/whitelist.js, lib/report/util.js, package-lock.json, package.json
=> add json output option and make report consistent

commands/report.js, commands/whitelist.js, lib/report/score.js, package-lock.json, package.json
This PR fixes the scoring mechanism for unknown licenses
=> fix scoring unknown licenses

bin/ncm-cli.js
=> bin: fixing bad DX for empty dir param

bin/ncm-cli.js
=> bin: bug fix
